### ISSUE TITLE
Installing font on OSX

### ISSUE THREAD

**Issue by pitxels** [allienworks/cryptocoins#12]
HI, I just added the font on OSX to use it in photoshop, but it doesn't seem to work. What I am missing here?

**Comment by allienworks** [comment]
Hey pitxels,

this is **not meant** as a ordinary font. It's rather an iconpack in _webfont_ format to be served on websites. It has mainly those reasons:

1. reducing server requests for all the icons you'd like to use on your websites (meaning faster loading, because you load only 1 file = webfont, not e.g. 15 files as separate SVGs)
2. there can be many options of styling fonts on websites — apart of color and background also shadow of a text etc. This makes webfont icons more customizable on the web.

If you want to use these in Photoshop, you'll need to download each one from the [SVG](https://github.com/allienworks/cryptocoins/tree/master/SVG) folder and then paste them in Illustrator. Then you can use them as ordinary vector shapes. It's a shame, but Photoshop unfortunately can't recognize SVG format.

_-OR-_

If you don't have Illustrator, you might try some tools to convert those SVGs into something more useful for Photoshop. I'd try [Cloud Convert](https://cloudconvert.com/svg-to-eps) (SVG => EPS), which should work (at least in theory :)

Let me know if you need anything else!
Cheers
