### ISSUE TITLE
Add ZEC Zcash

### ISSUE THREAD

**Issue by cryptonator** [allienworks/cryptocoins#23]
Could you please add Zcash ZEC? 

Current logo here: https://z.cash/press.html

Thank you!

**Comment by allienworks** [comment]
Hey @cryptonator, new release is out, this update included. Thanks for info and enjoy!

**Comment by vanlooverenkoen** [comment]
You said it was added but I can't find it anywhere in the ttf files from your website. please add to your ttf font on your website

**Comment by buzztiaan** [comment]
https://github.com/allienworks/cryptocoins/blob/master/SVG/ZEC.svg

from readme; 

Since 2.2 update, webfont version isn't included by default. I will release webfont versions less often as it seems like nobody's really using it. Sucks? Learn how to generate webfont by yourself – it's even better when you only include those you really need.

**Comment by vanlooverenkoen** [comment]
Is there an easy way to add them to the ttf file that already exists? I realy use all the icons so it would be nice if I just had the 2.2 release.

**Comment by allienworks** [comment]
The easiest way is to generate the font from scratch. There are many tools to do that - just import the SVG icons and download.See https://allien.work/blog/howto-generate-icon-webfont                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: vanlooverenkoenSent: neděle, 4. června 2017 13:22To: allienworks/cryptocoinsReply To: allienworks/cryptocoinsCc: Martin Allien; State changeSubject: Re: [allienworks/cryptocoins] Add ZEC Zcash (#23)Is there an easy way to add them to the ttf file that already exists? I realy use all the icons so it would be nice if I just had the 2.2 release.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/allienworks/cryptocoins","title":"allienworks/cryptocoins","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/allienworks/cryptocoins"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vanlooverenkoen in #23: Is there an easy way to add them to the ttf file that already exists? I realy use all the icons so it would be nice if I just had the 2.2 release. "}],"action":{"name":"View Issue","url":"https://github.com/allienworks/cryptocoins/issues/23#issuecomment-306034123"}}}
